package com.dzpay.admin.common.dto.mall;

import java.util.Date;

public class TblcorpInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_NAME
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CONT_ID
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private Short contId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_TAX_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpTaxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_OWN_NAME
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpOwnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_OWN_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpOwnNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_ZIPCODE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpZipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_ADDR1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpAddr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_ADDR2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpAddr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_OWN_ZIPCODE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpOwnZipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_OWN_ADDR1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpOwnAddr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_OWN_ADDR2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpOwnAddr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_BIZ
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpBiz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_ITEM
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_IND_CD
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpIndCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_POST_ZIPCODE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpPostZipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_POST_ADDR1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpPostAddr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_POST_ADDR2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpPostAddr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_TEL1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpTel1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_TEL2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpTel2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_TEL3
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpTel3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_FAX1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpFax1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_FAX2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpFax2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_FAX3
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpFax3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_OWN_MOB1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpOwnMob1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_OWN_MOB2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpOwnMob2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_OWN_MOB3
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpOwnMob3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_EMAIL
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_URL
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CARD_MONTH_LIMIT_MONY
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private Short cardMonthLimitMony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.ETC_MONTH_LIMIT_MONY
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private Short etcMonthLimitMony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.OLD_CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private Short oldCorpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_LEVEL
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.USE_YN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String useYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.REG_DT
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private Date regDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.MOD_DT
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private Date modDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.REG_GUBN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String regGubn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CONTRACT_YN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String contractYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.REG_ID
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String regId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.CORP_TYPE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String corpType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.ECOMMERCE_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String ecommerceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.SALE_GUBN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String saleGubn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.MAKE_TYPE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String makeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.SITE_DESC
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String siteDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.PG_TYPE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String pgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.SITE_HOSTING_ID
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String siteHostingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.VENDER_GUBN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String venderGubn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.VENDER_PAY_YN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String venderPayYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.SHOP_TYPE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String shopType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.ERP_MEM_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String erpMemNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.MEM_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String memNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_INFO.TEMP_FLG
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    private String tempFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_ID
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_ID
     *
     * @param corpId the value for SKYPG.TBLCORP_INFO.CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpId(String corpId) {
        this.corpId = corpId == null ? null : corpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_NAME
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_NAME
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_NAME
     *
     * @param corpName the value for SKYPG.TBLCORP_INFO.CORP_NAME
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName == null ? null : corpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CONT_ID
     *
     * @return the value of SKYPG.TBLCORP_INFO.CONT_ID
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public Short getContId() {
        return contId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CONT_ID
     *
     * @param contId the value for SKYPG.TBLCORP_INFO.CONT_ID
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setContId(Short contId) {
        this.contId = contId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_TAX_NO
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_TAX_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpTaxNo() {
        return corpTaxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_TAX_NO
     *
     * @param corpTaxNo the value for SKYPG.TBLCORP_INFO.CORP_TAX_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpTaxNo(String corpTaxNo) {
        this.corpTaxNo = corpTaxNo == null ? null : corpTaxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_NO
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpNo() {
        return corpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_NO
     *
     * @param corpNo the value for SKYPG.TBLCORP_INFO.CORP_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpNo(String corpNo) {
        this.corpNo = corpNo == null ? null : corpNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_OWN_NAME
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_OWN_NAME
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpOwnName() {
        return corpOwnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_OWN_NAME
     *
     * @param corpOwnName the value for SKYPG.TBLCORP_INFO.CORP_OWN_NAME
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpOwnName(String corpOwnName) {
        this.corpOwnName = corpOwnName == null ? null : corpOwnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_OWN_NO
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_OWN_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpOwnNo() {
        return corpOwnNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_OWN_NO
     *
     * @param corpOwnNo the value for SKYPG.TBLCORP_INFO.CORP_OWN_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpOwnNo(String corpOwnNo) {
        this.corpOwnNo = corpOwnNo == null ? null : corpOwnNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_ZIPCODE
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_ZIPCODE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpZipcode() {
        return corpZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_ZIPCODE
     *
     * @param corpZipcode the value for SKYPG.TBLCORP_INFO.CORP_ZIPCODE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpZipcode(String corpZipcode) {
        this.corpZipcode = corpZipcode == null ? null : corpZipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_ADDR1
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_ADDR1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpAddr1() {
        return corpAddr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_ADDR1
     *
     * @param corpAddr1 the value for SKYPG.TBLCORP_INFO.CORP_ADDR1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpAddr1(String corpAddr1) {
        this.corpAddr1 = corpAddr1 == null ? null : corpAddr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_ADDR2
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_ADDR2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpAddr2() {
        return corpAddr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_ADDR2
     *
     * @param corpAddr2 the value for SKYPG.TBLCORP_INFO.CORP_ADDR2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpAddr2(String corpAddr2) {
        this.corpAddr2 = corpAddr2 == null ? null : corpAddr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_OWN_ZIPCODE
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_OWN_ZIPCODE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpOwnZipcode() {
        return corpOwnZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_OWN_ZIPCODE
     *
     * @param corpOwnZipcode the value for SKYPG.TBLCORP_INFO.CORP_OWN_ZIPCODE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpOwnZipcode(String corpOwnZipcode) {
        this.corpOwnZipcode = corpOwnZipcode == null ? null : corpOwnZipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_OWN_ADDR1
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_OWN_ADDR1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpOwnAddr1() {
        return corpOwnAddr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_OWN_ADDR1
     *
     * @param corpOwnAddr1 the value for SKYPG.TBLCORP_INFO.CORP_OWN_ADDR1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpOwnAddr1(String corpOwnAddr1) {
        this.corpOwnAddr1 = corpOwnAddr1 == null ? null : corpOwnAddr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_OWN_ADDR2
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_OWN_ADDR2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpOwnAddr2() {
        return corpOwnAddr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_OWN_ADDR2
     *
     * @param corpOwnAddr2 the value for SKYPG.TBLCORP_INFO.CORP_OWN_ADDR2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpOwnAddr2(String corpOwnAddr2) {
        this.corpOwnAddr2 = corpOwnAddr2 == null ? null : corpOwnAddr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_BIZ
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_BIZ
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpBiz() {
        return corpBiz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_BIZ
     *
     * @param corpBiz the value for SKYPG.TBLCORP_INFO.CORP_BIZ
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpBiz(String corpBiz) {
        this.corpBiz = corpBiz == null ? null : corpBiz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_ITEM
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_ITEM
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpItem() {
        return corpItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_ITEM
     *
     * @param corpItem the value for SKYPG.TBLCORP_INFO.CORP_ITEM
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpItem(String corpItem) {
        this.corpItem = corpItem == null ? null : corpItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_IND_CD
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_IND_CD
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpIndCd() {
        return corpIndCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_IND_CD
     *
     * @param corpIndCd the value for SKYPG.TBLCORP_INFO.CORP_IND_CD
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpIndCd(String corpIndCd) {
        this.corpIndCd = corpIndCd == null ? null : corpIndCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_POST_ZIPCODE
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_POST_ZIPCODE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpPostZipcode() {
        return corpPostZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_POST_ZIPCODE
     *
     * @param corpPostZipcode the value for SKYPG.TBLCORP_INFO.CORP_POST_ZIPCODE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpPostZipcode(String corpPostZipcode) {
        this.corpPostZipcode = corpPostZipcode == null ? null : corpPostZipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_POST_ADDR1
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_POST_ADDR1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpPostAddr1() {
        return corpPostAddr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_POST_ADDR1
     *
     * @param corpPostAddr1 the value for SKYPG.TBLCORP_INFO.CORP_POST_ADDR1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpPostAddr1(String corpPostAddr1) {
        this.corpPostAddr1 = corpPostAddr1 == null ? null : corpPostAddr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_POST_ADDR2
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_POST_ADDR2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpPostAddr2() {
        return corpPostAddr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_POST_ADDR2
     *
     * @param corpPostAddr2 the value for SKYPG.TBLCORP_INFO.CORP_POST_ADDR2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpPostAddr2(String corpPostAddr2) {
        this.corpPostAddr2 = corpPostAddr2 == null ? null : corpPostAddr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_TEL1
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_TEL1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpTel1() {
        return corpTel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_TEL1
     *
     * @param corpTel1 the value for SKYPG.TBLCORP_INFO.CORP_TEL1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpTel1(String corpTel1) {
        this.corpTel1 = corpTel1 == null ? null : corpTel1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_TEL2
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_TEL2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpTel2() {
        return corpTel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_TEL2
     *
     * @param corpTel2 the value for SKYPG.TBLCORP_INFO.CORP_TEL2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpTel2(String corpTel2) {
        this.corpTel2 = corpTel2 == null ? null : corpTel2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_TEL3
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_TEL3
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpTel3() {
        return corpTel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_TEL3
     *
     * @param corpTel3 the value for SKYPG.TBLCORP_INFO.CORP_TEL3
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpTel3(String corpTel3) {
        this.corpTel3 = corpTel3 == null ? null : corpTel3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_FAX1
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_FAX1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpFax1() {
        return corpFax1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_FAX1
     *
     * @param corpFax1 the value for SKYPG.TBLCORP_INFO.CORP_FAX1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpFax1(String corpFax1) {
        this.corpFax1 = corpFax1 == null ? null : corpFax1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_FAX2
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_FAX2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpFax2() {
        return corpFax2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_FAX2
     *
     * @param corpFax2 the value for SKYPG.TBLCORP_INFO.CORP_FAX2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpFax2(String corpFax2) {
        this.corpFax2 = corpFax2 == null ? null : corpFax2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_FAX3
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_FAX3
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpFax3() {
        return corpFax3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_FAX3
     *
     * @param corpFax3 the value for SKYPG.TBLCORP_INFO.CORP_FAX3
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpFax3(String corpFax3) {
        this.corpFax3 = corpFax3 == null ? null : corpFax3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_OWN_MOB1
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_OWN_MOB1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpOwnMob1() {
        return corpOwnMob1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_OWN_MOB1
     *
     * @param corpOwnMob1 the value for SKYPG.TBLCORP_INFO.CORP_OWN_MOB1
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpOwnMob1(String corpOwnMob1) {
        this.corpOwnMob1 = corpOwnMob1 == null ? null : corpOwnMob1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_OWN_MOB2
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_OWN_MOB2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpOwnMob2() {
        return corpOwnMob2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_OWN_MOB2
     *
     * @param corpOwnMob2 the value for SKYPG.TBLCORP_INFO.CORP_OWN_MOB2
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpOwnMob2(String corpOwnMob2) {
        this.corpOwnMob2 = corpOwnMob2 == null ? null : corpOwnMob2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_OWN_MOB3
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_OWN_MOB3
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpOwnMob3() {
        return corpOwnMob3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_OWN_MOB3
     *
     * @param corpOwnMob3 the value for SKYPG.TBLCORP_INFO.CORP_OWN_MOB3
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpOwnMob3(String corpOwnMob3) {
        this.corpOwnMob3 = corpOwnMob3 == null ? null : corpOwnMob3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_EMAIL
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_EMAIL
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpEmail() {
        return corpEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_EMAIL
     *
     * @param corpEmail the value for SKYPG.TBLCORP_INFO.CORP_EMAIL
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpEmail(String corpEmail) {
        this.corpEmail = corpEmail == null ? null : corpEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_URL
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_URL
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpUrl() {
        return corpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_URL
     *
     * @param corpUrl the value for SKYPG.TBLCORP_INFO.CORP_URL
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpUrl(String corpUrl) {
        this.corpUrl = corpUrl == null ? null : corpUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CARD_MONTH_LIMIT_MONY
     *
     * @return the value of SKYPG.TBLCORP_INFO.CARD_MONTH_LIMIT_MONY
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public Short getCardMonthLimitMony() {
        return cardMonthLimitMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CARD_MONTH_LIMIT_MONY
     *
     * @param cardMonthLimitMony the value for SKYPG.TBLCORP_INFO.CARD_MONTH_LIMIT_MONY
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCardMonthLimitMony(Short cardMonthLimitMony) {
        this.cardMonthLimitMony = cardMonthLimitMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.ETC_MONTH_LIMIT_MONY
     *
     * @return the value of SKYPG.TBLCORP_INFO.ETC_MONTH_LIMIT_MONY
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public Short getEtcMonthLimitMony() {
        return etcMonthLimitMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.ETC_MONTH_LIMIT_MONY
     *
     * @param etcMonthLimitMony the value for SKYPG.TBLCORP_INFO.ETC_MONTH_LIMIT_MONY
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setEtcMonthLimitMony(Short etcMonthLimitMony) {
        this.etcMonthLimitMony = etcMonthLimitMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.OLD_CORP_ID
     *
     * @return the value of SKYPG.TBLCORP_INFO.OLD_CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public Short getOldCorpId() {
        return oldCorpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.OLD_CORP_ID
     *
     * @param oldCorpId the value for SKYPG.TBLCORP_INFO.OLD_CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setOldCorpId(Short oldCorpId) {
        this.oldCorpId = oldCorpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_LEVEL
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_LEVEL
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpLevel() {
        return corpLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_LEVEL
     *
     * @param corpLevel the value for SKYPG.TBLCORP_INFO.CORP_LEVEL
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpLevel(String corpLevel) {
        this.corpLevel = corpLevel == null ? null : corpLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.USE_YN
     *
     * @return the value of SKYPG.TBLCORP_INFO.USE_YN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.USE_YN
     *
     * @param useYn the value for SKYPG.TBLCORP_INFO.USE_YN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn == null ? null : useYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.REG_DT
     *
     * @return the value of SKYPG.TBLCORP_INFO.REG_DT
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public Date getRegDt() {
        return regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.REG_DT
     *
     * @param regDt the value for SKYPG.TBLCORP_INFO.REG_DT
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setRegDt(Date regDt) {
        this.regDt = regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.MOD_DT
     *
     * @return the value of SKYPG.TBLCORP_INFO.MOD_DT
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public Date getModDt() {
        return modDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.MOD_DT
     *
     * @param modDt the value for SKYPG.TBLCORP_INFO.MOD_DT
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setModDt(Date modDt) {
        this.modDt = modDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.REG_GUBN
     *
     * @return the value of SKYPG.TBLCORP_INFO.REG_GUBN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getRegGubn() {
        return regGubn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.REG_GUBN
     *
     * @param regGubn the value for SKYPG.TBLCORP_INFO.REG_GUBN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setRegGubn(String regGubn) {
        this.regGubn = regGubn == null ? null : regGubn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CONTRACT_YN
     *
     * @return the value of SKYPG.TBLCORP_INFO.CONTRACT_YN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getContractYn() {
        return contractYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CONTRACT_YN
     *
     * @param contractYn the value for SKYPG.TBLCORP_INFO.CONTRACT_YN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setContractYn(String contractYn) {
        this.contractYn = contractYn == null ? null : contractYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.REG_ID
     *
     * @return the value of SKYPG.TBLCORP_INFO.REG_ID
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.REG_ID
     *
     * @param regId the value for SKYPG.TBLCORP_INFO.REG_ID
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setRegId(String regId) {
        this.regId = regId == null ? null : regId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.CORP_TYPE
     *
     * @return the value of SKYPG.TBLCORP_INFO.CORP_TYPE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getCorpType() {
        return corpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.CORP_TYPE
     *
     * @param corpType the value for SKYPG.TBLCORP_INFO.CORP_TYPE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setCorpType(String corpType) {
        this.corpType = corpType == null ? null : corpType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.ECOMMERCE_NO
     *
     * @return the value of SKYPG.TBLCORP_INFO.ECOMMERCE_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getEcommerceNo() {
        return ecommerceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.ECOMMERCE_NO
     *
     * @param ecommerceNo the value for SKYPG.TBLCORP_INFO.ECOMMERCE_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setEcommerceNo(String ecommerceNo) {
        this.ecommerceNo = ecommerceNo == null ? null : ecommerceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.SALE_GUBN
     *
     * @return the value of SKYPG.TBLCORP_INFO.SALE_GUBN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getSaleGubn() {
        return saleGubn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.SALE_GUBN
     *
     * @param saleGubn the value for SKYPG.TBLCORP_INFO.SALE_GUBN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setSaleGubn(String saleGubn) {
        this.saleGubn = saleGubn == null ? null : saleGubn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.MAKE_TYPE
     *
     * @return the value of SKYPG.TBLCORP_INFO.MAKE_TYPE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getMakeType() {
        return makeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.MAKE_TYPE
     *
     * @param makeType the value for SKYPG.TBLCORP_INFO.MAKE_TYPE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setMakeType(String makeType) {
        this.makeType = makeType == null ? null : makeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.SITE_DESC
     *
     * @return the value of SKYPG.TBLCORP_INFO.SITE_DESC
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getSiteDesc() {
        return siteDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.SITE_DESC
     *
     * @param siteDesc the value for SKYPG.TBLCORP_INFO.SITE_DESC
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setSiteDesc(String siteDesc) {
        this.siteDesc = siteDesc == null ? null : siteDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.PG_TYPE
     *
     * @return the value of SKYPG.TBLCORP_INFO.PG_TYPE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getPgType() {
        return pgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.PG_TYPE
     *
     * @param pgType the value for SKYPG.TBLCORP_INFO.PG_TYPE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setPgType(String pgType) {
        this.pgType = pgType == null ? null : pgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.SITE_HOSTING_ID
     *
     * @return the value of SKYPG.TBLCORP_INFO.SITE_HOSTING_ID
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getSiteHostingId() {
        return siteHostingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.SITE_HOSTING_ID
     *
     * @param siteHostingId the value for SKYPG.TBLCORP_INFO.SITE_HOSTING_ID
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setSiteHostingId(String siteHostingId) {
        this.siteHostingId = siteHostingId == null ? null : siteHostingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.VENDER_GUBN
     *
     * @return the value of SKYPG.TBLCORP_INFO.VENDER_GUBN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getVenderGubn() {
        return venderGubn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.VENDER_GUBN
     *
     * @param venderGubn the value for SKYPG.TBLCORP_INFO.VENDER_GUBN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setVenderGubn(String venderGubn) {
        this.venderGubn = venderGubn == null ? null : venderGubn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.VENDER_PAY_YN
     *
     * @return the value of SKYPG.TBLCORP_INFO.VENDER_PAY_YN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getVenderPayYn() {
        return venderPayYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.VENDER_PAY_YN
     *
     * @param venderPayYn the value for SKYPG.TBLCORP_INFO.VENDER_PAY_YN
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setVenderPayYn(String venderPayYn) {
        this.venderPayYn = venderPayYn == null ? null : venderPayYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.SHOP_TYPE
     *
     * @return the value of SKYPG.TBLCORP_INFO.SHOP_TYPE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getShopType() {
        return shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.SHOP_TYPE
     *
     * @param shopType the value for SKYPG.TBLCORP_INFO.SHOP_TYPE
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setShopType(String shopType) {
        this.shopType = shopType == null ? null : shopType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.ERP_MEM_NO
     *
     * @return the value of SKYPG.TBLCORP_INFO.ERP_MEM_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getErpMemNo() {
        return erpMemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.ERP_MEM_NO
     *
     * @param erpMemNo the value for SKYPG.TBLCORP_INFO.ERP_MEM_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setErpMemNo(String erpMemNo) {
        this.erpMemNo = erpMemNo == null ? null : erpMemNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.MEM_NO
     *
     * @return the value of SKYPG.TBLCORP_INFO.MEM_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getMemNo() {
        return memNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.MEM_NO
     *
     * @param memNo the value for SKYPG.TBLCORP_INFO.MEM_NO
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setMemNo(String memNo) {
        this.memNo = memNo == null ? null : memNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_INFO.TEMP_FLG
     *
     * @return the value of SKYPG.TBLCORP_INFO.TEMP_FLG
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public String getTempFlg() {
        return tempFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_INFO.TEMP_FLG
     *
     * @param tempFlg the value for SKYPG.TBLCORP_INFO.TEMP_FLG
     *
     * @mbg.generated Thu Sep 10 09:41:52 KST 2020
     */
    public void setTempFlg(String tempFlg) {
        this.tempFlg = tempFlg == null ? null : tempFlg.trim();
    }
}