package com.dzpay.admin.common.dto.mall;

public class TblcorpCharge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_CHARGE.CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    private String corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_CHARGE.SITE_CD
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    private String siteCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_CHARGE.CHG_NM
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    private String chgNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_CHARGE.CHG_TYPE
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    private String chgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_CHARGE.CHG_DESC
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    private String chgDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_CHARGE.CHG_SEQ
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    private Short chgSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_CHARGE.JOB_GRD
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    private String jobGrd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_CHARGE.REG_ID
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    private String regId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_CHARGE.CHG_TEL1
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    private String chgTel1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_CHARGE.CHG_TEL2
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    private String chgTel2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_CHARGE.CHG_TEL3
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    private String chgTel3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_CHARGE.CHG_EMAIL
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    private String chgEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_CHARGE.CHG_MOB1
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    private String chgMob1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_CHARGE.CHG_MOB2
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    private String chgMob2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_CHARGE.CHG_MOB3
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    private String chgMob3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLCORP_CHARGE.JOB_GRD_NM
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    private String jobGrdNm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_CHARGE.CORP_ID
     *
     * @return the value of SKYPG.TBLCORP_CHARGE.CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public String getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_CHARGE.CORP_ID
     *
     * @param corpId the value for SKYPG.TBLCORP_CHARGE.CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public void setCorpId(String corpId) {
        this.corpId = corpId == null ? null : corpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_CHARGE.SITE_CD
     *
     * @return the value of SKYPG.TBLCORP_CHARGE.SITE_CD
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public String getSiteCd() {
        return siteCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_CHARGE.SITE_CD
     *
     * @param siteCd the value for SKYPG.TBLCORP_CHARGE.SITE_CD
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public void setSiteCd(String siteCd) {
        this.siteCd = siteCd == null ? null : siteCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_CHARGE.CHG_NM
     *
     * @return the value of SKYPG.TBLCORP_CHARGE.CHG_NM
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public String getChgNm() {
        return chgNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_CHARGE.CHG_NM
     *
     * @param chgNm the value for SKYPG.TBLCORP_CHARGE.CHG_NM
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public void setChgNm(String chgNm) {
        this.chgNm = chgNm == null ? null : chgNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_CHARGE.CHG_TYPE
     *
     * @return the value of SKYPG.TBLCORP_CHARGE.CHG_TYPE
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public String getChgType() {
        return chgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_CHARGE.CHG_TYPE
     *
     * @param chgType the value for SKYPG.TBLCORP_CHARGE.CHG_TYPE
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public void setChgType(String chgType) {
        this.chgType = chgType == null ? null : chgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_CHARGE.CHG_DESC
     *
     * @return the value of SKYPG.TBLCORP_CHARGE.CHG_DESC
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public String getChgDesc() {
        return chgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_CHARGE.CHG_DESC
     *
     * @param chgDesc the value for SKYPG.TBLCORP_CHARGE.CHG_DESC
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public void setChgDesc(String chgDesc) {
        this.chgDesc = chgDesc == null ? null : chgDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_CHARGE.CHG_SEQ
     *
     * @return the value of SKYPG.TBLCORP_CHARGE.CHG_SEQ
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public Short getChgSeq() {
        return chgSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_CHARGE.CHG_SEQ
     *
     * @param chgSeq the value for SKYPG.TBLCORP_CHARGE.CHG_SEQ
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public void setChgSeq(Short chgSeq) {
        this.chgSeq = chgSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_CHARGE.JOB_GRD
     *
     * @return the value of SKYPG.TBLCORP_CHARGE.JOB_GRD
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public String getJobGrd() {
        return jobGrd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_CHARGE.JOB_GRD
     *
     * @param jobGrd the value for SKYPG.TBLCORP_CHARGE.JOB_GRD
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public void setJobGrd(String jobGrd) {
        this.jobGrd = jobGrd == null ? null : jobGrd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_CHARGE.REG_ID
     *
     * @return the value of SKYPG.TBLCORP_CHARGE.REG_ID
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_CHARGE.REG_ID
     *
     * @param regId the value for SKYPG.TBLCORP_CHARGE.REG_ID
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public void setRegId(String regId) {
        this.regId = regId == null ? null : regId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_CHARGE.CHG_TEL1
     *
     * @return the value of SKYPG.TBLCORP_CHARGE.CHG_TEL1
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public String getChgTel1() {
        return chgTel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_CHARGE.CHG_TEL1
     *
     * @param chgTel1 the value for SKYPG.TBLCORP_CHARGE.CHG_TEL1
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public void setChgTel1(String chgTel1) {
        this.chgTel1 = chgTel1 == null ? null : chgTel1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_CHARGE.CHG_TEL2
     *
     * @return the value of SKYPG.TBLCORP_CHARGE.CHG_TEL2
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public String getChgTel2() {
        return chgTel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_CHARGE.CHG_TEL2
     *
     * @param chgTel2 the value for SKYPG.TBLCORP_CHARGE.CHG_TEL2
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public void setChgTel2(String chgTel2) {
        this.chgTel2 = chgTel2 == null ? null : chgTel2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_CHARGE.CHG_TEL3
     *
     * @return the value of SKYPG.TBLCORP_CHARGE.CHG_TEL3
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public String getChgTel3() {
        return chgTel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_CHARGE.CHG_TEL3
     *
     * @param chgTel3 the value for SKYPG.TBLCORP_CHARGE.CHG_TEL3
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public void setChgTel3(String chgTel3) {
        this.chgTel3 = chgTel3 == null ? null : chgTel3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_CHARGE.CHG_EMAIL
     *
     * @return the value of SKYPG.TBLCORP_CHARGE.CHG_EMAIL
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public String getChgEmail() {
        return chgEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_CHARGE.CHG_EMAIL
     *
     * @param chgEmail the value for SKYPG.TBLCORP_CHARGE.CHG_EMAIL
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public void setChgEmail(String chgEmail) {
        this.chgEmail = chgEmail == null ? null : chgEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_CHARGE.CHG_MOB1
     *
     * @return the value of SKYPG.TBLCORP_CHARGE.CHG_MOB1
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public String getChgMob1() {
        return chgMob1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_CHARGE.CHG_MOB1
     *
     * @param chgMob1 the value for SKYPG.TBLCORP_CHARGE.CHG_MOB1
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public void setChgMob1(String chgMob1) {
        this.chgMob1 = chgMob1 == null ? null : chgMob1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_CHARGE.CHG_MOB2
     *
     * @return the value of SKYPG.TBLCORP_CHARGE.CHG_MOB2
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public String getChgMob2() {
        return chgMob2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_CHARGE.CHG_MOB2
     *
     * @param chgMob2 the value for SKYPG.TBLCORP_CHARGE.CHG_MOB2
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public void setChgMob2(String chgMob2) {
        this.chgMob2 = chgMob2 == null ? null : chgMob2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_CHARGE.CHG_MOB3
     *
     * @return the value of SKYPG.TBLCORP_CHARGE.CHG_MOB3
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public String getChgMob3() {
        return chgMob3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_CHARGE.CHG_MOB3
     *
     * @param chgMob3 the value for SKYPG.TBLCORP_CHARGE.CHG_MOB3
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public void setChgMob3(String chgMob3) {
        this.chgMob3 = chgMob3 == null ? null : chgMob3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLCORP_CHARGE.JOB_GRD_NM
     *
     * @return the value of SKYPG.TBLCORP_CHARGE.JOB_GRD_NM
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public String getJobGrdNm() {
        return jobGrdNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLCORP_CHARGE.JOB_GRD_NM
     *
     * @param jobGrdNm the value for SKYPG.TBLCORP_CHARGE.JOB_GRD_NM
     *
     * @mbg.generated Thu Sep 10 09:26:37 KST 2020
     */
    public void setJobGrdNm(String jobGrdNm) {
        this.jobGrdNm = jobGrdNm == null ? null : jobGrdNm.trim();
    }
}