package com.dzpay.admin.common.dto.mall;

import java.util.Date;

public class TblsiteInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SITE_CD
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String siteCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SITE_NAME
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String siteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SITE_TEL_NO1
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String siteTelNo1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SITE_TEL_NO2
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String siteTelNo2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SITE_TEL_NO3
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String siteTelNo3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SITE_FAX_NO1
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String siteFaxNo1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SITE_FAX_NO2
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String siteFaxNo2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SITE_FAX_NO3
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String siteFaxNo3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SITE_EMAIL
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String siteEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SITE_URL
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String siteUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.REG_DT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private Date regDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.MOD_DT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private Date modDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.MOD_ADMIN_ID
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String modAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.USE_YN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String useYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.CHG_ID
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String chgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SITE_TAX_TYPE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String siteTaxType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SITE_LEVEL
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String siteLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.OLD_CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String oldCorpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SEAL_NM
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String sealNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.EXAMINE_YN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String examineYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.EXAMINE_OPINION
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String examineOpinion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.EXAMINE_COMMENTS
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String examineComments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.YEAR_MONY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private Short yearMony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.JOIN_COST_MONY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private Short joinCostMony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.YEAR_MONY_LIMIT_DT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String yearMonyLimitDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.MEMBER_GUBN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String memberGubn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SERVICE_FEE_PAY_AMT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private Short serviceFeePayAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SERVICE_FEE_PAY_STAT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String serviceFeePayStat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.RESELLER_PAY_YN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String resellerPayYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SITE_DESC
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String siteDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SITE_MONY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private Short siteMony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.JOIN_COST_DT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String joinCostDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.RESELLER_PAY_MONY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private Short resellerPayMony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.RESELLER_RATE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private Short resellerRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.RESELLER_GUBN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String resellerGubn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SITE_STS
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String siteSts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.RESELLER_RATE_TYPE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String resellerRateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.RESELLER_FEE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private Short resellerFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SHOP_TYPE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String shopType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SALE_TYPE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String saleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SITE_VAN_CD
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String siteVanCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SALE_FOR
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String saleFor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.TAX_INC_YN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String taxIncYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.MEM_NO
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String memNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.TEMP_FLG
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String tempFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.API_KEY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String apiKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.ENC_KEY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String encKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLSITE_INFO.SITE_STS_DETAIL
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    private String siteStsDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SITE_CD
     *
     * @return the value of SKYPG.TBLSITE_INFO.SITE_CD
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSiteCd() {
        return siteCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SITE_CD
     *
     * @param siteCd the value for SKYPG.TBLSITE_INFO.SITE_CD
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSiteCd(String siteCd) {
        this.siteCd = siteCd == null ? null : siteCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.CORP_ID
     *
     * @return the value of SKYPG.TBLSITE_INFO.CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.CORP_ID
     *
     * @param corpId the value for SKYPG.TBLSITE_INFO.CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setCorpId(String corpId) {
        this.corpId = corpId == null ? null : corpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SITE_NAME
     *
     * @return the value of SKYPG.TBLSITE_INFO.SITE_NAME
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SITE_NAME
     *
     * @param siteName the value for SKYPG.TBLSITE_INFO.SITE_NAME
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName == null ? null : siteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SITE_TEL_NO1
     *
     * @return the value of SKYPG.TBLSITE_INFO.SITE_TEL_NO1
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSiteTelNo1() {
        return siteTelNo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SITE_TEL_NO1
     *
     * @param siteTelNo1 the value for SKYPG.TBLSITE_INFO.SITE_TEL_NO1
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSiteTelNo1(String siteTelNo1) {
        this.siteTelNo1 = siteTelNo1 == null ? null : siteTelNo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SITE_TEL_NO2
     *
     * @return the value of SKYPG.TBLSITE_INFO.SITE_TEL_NO2
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSiteTelNo2() {
        return siteTelNo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SITE_TEL_NO2
     *
     * @param siteTelNo2 the value for SKYPG.TBLSITE_INFO.SITE_TEL_NO2
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSiteTelNo2(String siteTelNo2) {
        this.siteTelNo2 = siteTelNo2 == null ? null : siteTelNo2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SITE_TEL_NO3
     *
     * @return the value of SKYPG.TBLSITE_INFO.SITE_TEL_NO3
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSiteTelNo3() {
        return siteTelNo3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SITE_TEL_NO3
     *
     * @param siteTelNo3 the value for SKYPG.TBLSITE_INFO.SITE_TEL_NO3
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSiteTelNo3(String siteTelNo3) {
        this.siteTelNo3 = siteTelNo3 == null ? null : siteTelNo3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SITE_FAX_NO1
     *
     * @return the value of SKYPG.TBLSITE_INFO.SITE_FAX_NO1
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSiteFaxNo1() {
        return siteFaxNo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SITE_FAX_NO1
     *
     * @param siteFaxNo1 the value for SKYPG.TBLSITE_INFO.SITE_FAX_NO1
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSiteFaxNo1(String siteFaxNo1) {
        this.siteFaxNo1 = siteFaxNo1 == null ? null : siteFaxNo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SITE_FAX_NO2
     *
     * @return the value of SKYPG.TBLSITE_INFO.SITE_FAX_NO2
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSiteFaxNo2() {
        return siteFaxNo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SITE_FAX_NO2
     *
     * @param siteFaxNo2 the value for SKYPG.TBLSITE_INFO.SITE_FAX_NO2
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSiteFaxNo2(String siteFaxNo2) {
        this.siteFaxNo2 = siteFaxNo2 == null ? null : siteFaxNo2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SITE_FAX_NO3
     *
     * @return the value of SKYPG.TBLSITE_INFO.SITE_FAX_NO3
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSiteFaxNo3() {
        return siteFaxNo3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SITE_FAX_NO3
     *
     * @param siteFaxNo3 the value for SKYPG.TBLSITE_INFO.SITE_FAX_NO3
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSiteFaxNo3(String siteFaxNo3) {
        this.siteFaxNo3 = siteFaxNo3 == null ? null : siteFaxNo3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SITE_EMAIL
     *
     * @return the value of SKYPG.TBLSITE_INFO.SITE_EMAIL
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSiteEmail() {
        return siteEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SITE_EMAIL
     *
     * @param siteEmail the value for SKYPG.TBLSITE_INFO.SITE_EMAIL
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSiteEmail(String siteEmail) {
        this.siteEmail = siteEmail == null ? null : siteEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SITE_URL
     *
     * @return the value of SKYPG.TBLSITE_INFO.SITE_URL
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSiteUrl() {
        return siteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SITE_URL
     *
     * @param siteUrl the value for SKYPG.TBLSITE_INFO.SITE_URL
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSiteUrl(String siteUrl) {
        this.siteUrl = siteUrl == null ? null : siteUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.REG_DT
     *
     * @return the value of SKYPG.TBLSITE_INFO.REG_DT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public Date getRegDt() {
        return regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.REG_DT
     *
     * @param regDt the value for SKYPG.TBLSITE_INFO.REG_DT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setRegDt(Date regDt) {
        this.regDt = regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.MOD_DT
     *
     * @return the value of SKYPG.TBLSITE_INFO.MOD_DT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public Date getModDt() {
        return modDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.MOD_DT
     *
     * @param modDt the value for SKYPG.TBLSITE_INFO.MOD_DT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setModDt(Date modDt) {
        this.modDt = modDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.MOD_ADMIN_ID
     *
     * @return the value of SKYPG.TBLSITE_INFO.MOD_ADMIN_ID
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getModAdminId() {
        return modAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.MOD_ADMIN_ID
     *
     * @param modAdminId the value for SKYPG.TBLSITE_INFO.MOD_ADMIN_ID
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setModAdminId(String modAdminId) {
        this.modAdminId = modAdminId == null ? null : modAdminId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.USE_YN
     *
     * @return the value of SKYPG.TBLSITE_INFO.USE_YN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.USE_YN
     *
     * @param useYn the value for SKYPG.TBLSITE_INFO.USE_YN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn == null ? null : useYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.CHG_ID
     *
     * @return the value of SKYPG.TBLSITE_INFO.CHG_ID
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getChgId() {
        return chgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.CHG_ID
     *
     * @param chgId the value for SKYPG.TBLSITE_INFO.CHG_ID
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setChgId(String chgId) {
        this.chgId = chgId == null ? null : chgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SITE_TAX_TYPE
     *
     * @return the value of SKYPG.TBLSITE_INFO.SITE_TAX_TYPE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSiteTaxType() {
        return siteTaxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SITE_TAX_TYPE
     *
     * @param siteTaxType the value for SKYPG.TBLSITE_INFO.SITE_TAX_TYPE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSiteTaxType(String siteTaxType) {
        this.siteTaxType = siteTaxType == null ? null : siteTaxType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SITE_LEVEL
     *
     * @return the value of SKYPG.TBLSITE_INFO.SITE_LEVEL
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSiteLevel() {
        return siteLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SITE_LEVEL
     *
     * @param siteLevel the value for SKYPG.TBLSITE_INFO.SITE_LEVEL
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSiteLevel(String siteLevel) {
        this.siteLevel = siteLevel == null ? null : siteLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.OLD_CORP_ID
     *
     * @return the value of SKYPG.TBLSITE_INFO.OLD_CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getOldCorpId() {
        return oldCorpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.OLD_CORP_ID
     *
     * @param oldCorpId the value for SKYPG.TBLSITE_INFO.OLD_CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setOldCorpId(String oldCorpId) {
        this.oldCorpId = oldCorpId == null ? null : oldCorpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SEAL_NM
     *
     * @return the value of SKYPG.TBLSITE_INFO.SEAL_NM
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSealNm() {
        return sealNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SEAL_NM
     *
     * @param sealNm the value for SKYPG.TBLSITE_INFO.SEAL_NM
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSealNm(String sealNm) {
        this.sealNm = sealNm == null ? null : sealNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.EXAMINE_YN
     *
     * @return the value of SKYPG.TBLSITE_INFO.EXAMINE_YN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getExamineYn() {
        return examineYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.EXAMINE_YN
     *
     * @param examineYn the value for SKYPG.TBLSITE_INFO.EXAMINE_YN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setExamineYn(String examineYn) {
        this.examineYn = examineYn == null ? null : examineYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.EXAMINE_OPINION
     *
     * @return the value of SKYPG.TBLSITE_INFO.EXAMINE_OPINION
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getExamineOpinion() {
        return examineOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.EXAMINE_OPINION
     *
     * @param examineOpinion the value for SKYPG.TBLSITE_INFO.EXAMINE_OPINION
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setExamineOpinion(String examineOpinion) {
        this.examineOpinion = examineOpinion == null ? null : examineOpinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.EXAMINE_COMMENTS
     *
     * @return the value of SKYPG.TBLSITE_INFO.EXAMINE_COMMENTS
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getExamineComments() {
        return examineComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.EXAMINE_COMMENTS
     *
     * @param examineComments the value for SKYPG.TBLSITE_INFO.EXAMINE_COMMENTS
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setExamineComments(String examineComments) {
        this.examineComments = examineComments == null ? null : examineComments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.YEAR_MONY
     *
     * @return the value of SKYPG.TBLSITE_INFO.YEAR_MONY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public Short getYearMony() {
        return yearMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.YEAR_MONY
     *
     * @param yearMony the value for SKYPG.TBLSITE_INFO.YEAR_MONY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setYearMony(Short yearMony) {
        this.yearMony = yearMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.JOIN_COST_MONY
     *
     * @return the value of SKYPG.TBLSITE_INFO.JOIN_COST_MONY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public Short getJoinCostMony() {
        return joinCostMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.JOIN_COST_MONY
     *
     * @param joinCostMony the value for SKYPG.TBLSITE_INFO.JOIN_COST_MONY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setJoinCostMony(Short joinCostMony) {
        this.joinCostMony = joinCostMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.YEAR_MONY_LIMIT_DT
     *
     * @return the value of SKYPG.TBLSITE_INFO.YEAR_MONY_LIMIT_DT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getYearMonyLimitDt() {
        return yearMonyLimitDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.YEAR_MONY_LIMIT_DT
     *
     * @param yearMonyLimitDt the value for SKYPG.TBLSITE_INFO.YEAR_MONY_LIMIT_DT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setYearMonyLimitDt(String yearMonyLimitDt) {
        this.yearMonyLimitDt = yearMonyLimitDt == null ? null : yearMonyLimitDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.MEMBER_GUBN
     *
     * @return the value of SKYPG.TBLSITE_INFO.MEMBER_GUBN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getMemberGubn() {
        return memberGubn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.MEMBER_GUBN
     *
     * @param memberGubn the value for SKYPG.TBLSITE_INFO.MEMBER_GUBN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setMemberGubn(String memberGubn) {
        this.memberGubn = memberGubn == null ? null : memberGubn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SERVICE_FEE_PAY_AMT
     *
     * @return the value of SKYPG.TBLSITE_INFO.SERVICE_FEE_PAY_AMT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public Short getServiceFeePayAmt() {
        return serviceFeePayAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SERVICE_FEE_PAY_AMT
     *
     * @param serviceFeePayAmt the value for SKYPG.TBLSITE_INFO.SERVICE_FEE_PAY_AMT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setServiceFeePayAmt(Short serviceFeePayAmt) {
        this.serviceFeePayAmt = serviceFeePayAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SERVICE_FEE_PAY_STAT
     *
     * @return the value of SKYPG.TBLSITE_INFO.SERVICE_FEE_PAY_STAT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getServiceFeePayStat() {
        return serviceFeePayStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SERVICE_FEE_PAY_STAT
     *
     * @param serviceFeePayStat the value for SKYPG.TBLSITE_INFO.SERVICE_FEE_PAY_STAT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setServiceFeePayStat(String serviceFeePayStat) {
        this.serviceFeePayStat = serviceFeePayStat == null ? null : serviceFeePayStat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.RESELLER_PAY_YN
     *
     * @return the value of SKYPG.TBLSITE_INFO.RESELLER_PAY_YN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getResellerPayYn() {
        return resellerPayYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.RESELLER_PAY_YN
     *
     * @param resellerPayYn the value for SKYPG.TBLSITE_INFO.RESELLER_PAY_YN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setResellerPayYn(String resellerPayYn) {
        this.resellerPayYn = resellerPayYn == null ? null : resellerPayYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SITE_DESC
     *
     * @return the value of SKYPG.TBLSITE_INFO.SITE_DESC
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSiteDesc() {
        return siteDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SITE_DESC
     *
     * @param siteDesc the value for SKYPG.TBLSITE_INFO.SITE_DESC
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSiteDesc(String siteDesc) {
        this.siteDesc = siteDesc == null ? null : siteDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SITE_MONY
     *
     * @return the value of SKYPG.TBLSITE_INFO.SITE_MONY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public Short getSiteMony() {
        return siteMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SITE_MONY
     *
     * @param siteMony the value for SKYPG.TBLSITE_INFO.SITE_MONY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSiteMony(Short siteMony) {
        this.siteMony = siteMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.JOIN_COST_DT
     *
     * @return the value of SKYPG.TBLSITE_INFO.JOIN_COST_DT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getJoinCostDt() {
        return joinCostDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.JOIN_COST_DT
     *
     * @param joinCostDt the value for SKYPG.TBLSITE_INFO.JOIN_COST_DT
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setJoinCostDt(String joinCostDt) {
        this.joinCostDt = joinCostDt == null ? null : joinCostDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.RESELLER_PAY_MONY
     *
     * @return the value of SKYPG.TBLSITE_INFO.RESELLER_PAY_MONY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public Short getResellerPayMony() {
        return resellerPayMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.RESELLER_PAY_MONY
     *
     * @param resellerPayMony the value for SKYPG.TBLSITE_INFO.RESELLER_PAY_MONY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setResellerPayMony(Short resellerPayMony) {
        this.resellerPayMony = resellerPayMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.RESELLER_RATE
     *
     * @return the value of SKYPG.TBLSITE_INFO.RESELLER_RATE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public Short getResellerRate() {
        return resellerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.RESELLER_RATE
     *
     * @param resellerRate the value for SKYPG.TBLSITE_INFO.RESELLER_RATE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setResellerRate(Short resellerRate) {
        this.resellerRate = resellerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.RESELLER_GUBN
     *
     * @return the value of SKYPG.TBLSITE_INFO.RESELLER_GUBN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getResellerGubn() {
        return resellerGubn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.RESELLER_GUBN
     *
     * @param resellerGubn the value for SKYPG.TBLSITE_INFO.RESELLER_GUBN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setResellerGubn(String resellerGubn) {
        this.resellerGubn = resellerGubn == null ? null : resellerGubn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SITE_STS
     *
     * @return the value of SKYPG.TBLSITE_INFO.SITE_STS
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSiteSts() {
        return siteSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SITE_STS
     *
     * @param siteSts the value for SKYPG.TBLSITE_INFO.SITE_STS
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSiteSts(String siteSts) {
        this.siteSts = siteSts == null ? null : siteSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.RESELLER_RATE_TYPE
     *
     * @return the value of SKYPG.TBLSITE_INFO.RESELLER_RATE_TYPE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getResellerRateType() {
        return resellerRateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.RESELLER_RATE_TYPE
     *
     * @param resellerRateType the value for SKYPG.TBLSITE_INFO.RESELLER_RATE_TYPE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setResellerRateType(String resellerRateType) {
        this.resellerRateType = resellerRateType == null ? null : resellerRateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.RESELLER_FEE
     *
     * @return the value of SKYPG.TBLSITE_INFO.RESELLER_FEE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public Short getResellerFee() {
        return resellerFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.RESELLER_FEE
     *
     * @param resellerFee the value for SKYPG.TBLSITE_INFO.RESELLER_FEE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setResellerFee(Short resellerFee) {
        this.resellerFee = resellerFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SHOP_TYPE
     *
     * @return the value of SKYPG.TBLSITE_INFO.SHOP_TYPE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getShopType() {
        return shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SHOP_TYPE
     *
     * @param shopType the value for SKYPG.TBLSITE_INFO.SHOP_TYPE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setShopType(String shopType) {
        this.shopType = shopType == null ? null : shopType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SALE_TYPE
     *
     * @return the value of SKYPG.TBLSITE_INFO.SALE_TYPE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSaleType() {
        return saleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SALE_TYPE
     *
     * @param saleType the value for SKYPG.TBLSITE_INFO.SALE_TYPE
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSaleType(String saleType) {
        this.saleType = saleType == null ? null : saleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SITE_VAN_CD
     *
     * @return the value of SKYPG.TBLSITE_INFO.SITE_VAN_CD
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSiteVanCd() {
        return siteVanCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SITE_VAN_CD
     *
     * @param siteVanCd the value for SKYPG.TBLSITE_INFO.SITE_VAN_CD
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSiteVanCd(String siteVanCd) {
        this.siteVanCd = siteVanCd == null ? null : siteVanCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SALE_FOR
     *
     * @return the value of SKYPG.TBLSITE_INFO.SALE_FOR
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSaleFor() {
        return saleFor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SALE_FOR
     *
     * @param saleFor the value for SKYPG.TBLSITE_INFO.SALE_FOR
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSaleFor(String saleFor) {
        this.saleFor = saleFor == null ? null : saleFor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.TAX_INC_YN
     *
     * @return the value of SKYPG.TBLSITE_INFO.TAX_INC_YN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getTaxIncYn() {
        return taxIncYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.TAX_INC_YN
     *
     * @param taxIncYn the value for SKYPG.TBLSITE_INFO.TAX_INC_YN
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setTaxIncYn(String taxIncYn) {
        this.taxIncYn = taxIncYn == null ? null : taxIncYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.MEM_NO
     *
     * @return the value of SKYPG.TBLSITE_INFO.MEM_NO
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getMemNo() {
        return memNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.MEM_NO
     *
     * @param memNo the value for SKYPG.TBLSITE_INFO.MEM_NO
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setMemNo(String memNo) {
        this.memNo = memNo == null ? null : memNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.TEMP_FLG
     *
     * @return the value of SKYPG.TBLSITE_INFO.TEMP_FLG
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getTempFlg() {
        return tempFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.TEMP_FLG
     *
     * @param tempFlg the value for SKYPG.TBLSITE_INFO.TEMP_FLG
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setTempFlg(String tempFlg) {
        this.tempFlg = tempFlg == null ? null : tempFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.API_KEY
     *
     * @return the value of SKYPG.TBLSITE_INFO.API_KEY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getApiKey() {
        return apiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.API_KEY
     *
     * @param apiKey the value for SKYPG.TBLSITE_INFO.API_KEY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setApiKey(String apiKey) {
        this.apiKey = apiKey == null ? null : apiKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.ENC_KEY
     *
     * @return the value of SKYPG.TBLSITE_INFO.ENC_KEY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getEncKey() {
        return encKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.ENC_KEY
     *
     * @param encKey the value for SKYPG.TBLSITE_INFO.ENC_KEY
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setEncKey(String encKey) {
        this.encKey = encKey == null ? null : encKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLSITE_INFO.SITE_STS_DETAIL
     *
     * @return the value of SKYPG.TBLSITE_INFO.SITE_STS_DETAIL
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public String getSiteStsDetail() {
        return siteStsDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLSITE_INFO.SITE_STS_DETAIL
     *
     * @param siteStsDetail the value for SKYPG.TBLSITE_INFO.SITE_STS_DETAIL
     *
     * @mbg.generated Thu Sep 10 09:28:21 KST 2020
     */
    public void setSiteStsDetail(String siteStsDetail) {
        this.siteStsDetail = siteStsDetail == null ? null : siteStsDetail.trim();
    }
}