package com.dzpay.admin.common.dto.sms;

import java.util.Date;


public class MsgQueue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.MSEQ
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Long mseq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.MSG_TYPE
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String msgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.SEND_TYPE
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String sendType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.DKEY
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String dkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.DCNT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Long dcnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.DSTADDR
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String dstaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.CALLBACK
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String callback;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.STAT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String stat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.SUBJECT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.TEXT_TYPE
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String textType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.TEXT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.EXPIRETIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Integer expiretime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.FILECNT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Short filecnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.FILELOC1
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String fileloc1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.FILESIZE1
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Long filesize1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.FILELOC2
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String fileloc2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.FILESIZE2
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Long filesize2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.FILELOC3
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String fileloc3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.FILESIZE3
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Long filesize3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.FILELOC4
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String fileloc4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.FILESIZE4
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Long filesize4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.FILELOC5
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String fileloc5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.FILESIZE5
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Long filesize5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.FILECNT_CHECKUP
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Short filecntCheckup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.INSERT_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.REQUEST_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Date requestTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.SEND_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.REPORT_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Date reportTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.TCPRECV_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Date tcprecvTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.SAVE_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Date saveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.TELECOM
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String telecom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.RESULT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.REPCNT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Integer repcnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.SERVER_ID
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Long serverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.OPT_ID
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String optId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.OPT_CMP
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String optCmp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.OPT_POST
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String optPost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.OPT_NAME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String optName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.EXT_COL0
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private Long extCol0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.EXT_COL1
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String extCol1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.EXT_COL2
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String extCol2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.EXT_COL3
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String extCol3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.SITE_CD
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String siteCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.MSG_QUEUE.CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    private String corpId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.MSEQ
     *
     * @return the value of SKYPG.MSG_QUEUE.MSEQ
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Long getMseq() {
        return mseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.MSEQ
     *
     * @param mseq the value for SKYPG.MSG_QUEUE.MSEQ
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setMseq(Long mseq) {
        this.mseq = mseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.MSG_TYPE
     *
     * @return the value of SKYPG.MSG_QUEUE.MSG_TYPE
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.MSG_TYPE
     *
     * @param msgType the value for SKYPG.MSG_QUEUE.MSG_TYPE
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setMsgType(String msgType) {
        this.msgType = msgType == null ? null : msgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.SEND_TYPE
     *
     * @return the value of SKYPG.MSG_QUEUE.SEND_TYPE
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getSendType() {
        return sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.SEND_TYPE
     *
     * @param sendType the value for SKYPG.MSG_QUEUE.SEND_TYPE
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setSendType(String sendType) {
        this.sendType = sendType == null ? null : sendType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.DKEY
     *
     * @return the value of SKYPG.MSG_QUEUE.DKEY
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getDkey() {
        return dkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.DKEY
     *
     * @param dkey the value for SKYPG.MSG_QUEUE.DKEY
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setDkey(String dkey) {
        this.dkey = dkey == null ? null : dkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.DCNT
     *
     * @return the value of SKYPG.MSG_QUEUE.DCNT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Long getDcnt() {
        return dcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.DCNT
     *
     * @param dcnt the value for SKYPG.MSG_QUEUE.DCNT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setDcnt(Long dcnt) {
        this.dcnt = dcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.DSTADDR
     *
     * @return the value of SKYPG.MSG_QUEUE.DSTADDR
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getDstaddr() {
        return dstaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.DSTADDR
     *
     * @param dstaddr the value for SKYPG.MSG_QUEUE.DSTADDR
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setDstaddr(String dstaddr) {
        this.dstaddr = dstaddr == null ? null : dstaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.CALLBACK
     *
     * @return the value of SKYPG.MSG_QUEUE.CALLBACK
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getCallback() {
        return callback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.CALLBACK
     *
     * @param callback the value for SKYPG.MSG_QUEUE.CALLBACK
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setCallback(String callback) {
        this.callback = callback == null ? null : callback.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.STAT
     *
     * @return the value of SKYPG.MSG_QUEUE.STAT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.STAT
     *
     * @param stat the value for SKYPG.MSG_QUEUE.STAT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setStat(String stat) {
        this.stat = stat == null ? null : stat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.SUBJECT
     *
     * @return the value of SKYPG.MSG_QUEUE.SUBJECT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.SUBJECT
     *
     * @param subject the value for SKYPG.MSG_QUEUE.SUBJECT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.TEXT_TYPE
     *
     * @return the value of SKYPG.MSG_QUEUE.TEXT_TYPE
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getTextType() {
        return textType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.TEXT_TYPE
     *
     * @param textType the value for SKYPG.MSG_QUEUE.TEXT_TYPE
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setTextType(String textType) {
        this.textType = textType == null ? null : textType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.TEXT
     *
     * @return the value of SKYPG.MSG_QUEUE.TEXT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.TEXT
     *
     * @param text the value for SKYPG.MSG_QUEUE.TEXT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.EXPIRETIME
     *
     * @return the value of SKYPG.MSG_QUEUE.EXPIRETIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Integer getExpiretime() {
        return expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.EXPIRETIME
     *
     * @param expiretime the value for SKYPG.MSG_QUEUE.EXPIRETIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setExpiretime(Integer expiretime) {
        this.expiretime = expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.FILECNT
     *
     * @return the value of SKYPG.MSG_QUEUE.FILECNT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Short getFilecnt() {
        return filecnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.FILECNT
     *
     * @param filecnt the value for SKYPG.MSG_QUEUE.FILECNT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setFilecnt(Short filecnt) {
        this.filecnt = filecnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.FILELOC1
     *
     * @return the value of SKYPG.MSG_QUEUE.FILELOC1
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getFileloc1() {
        return fileloc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.FILELOC1
     *
     * @param fileloc1 the value for SKYPG.MSG_QUEUE.FILELOC1
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setFileloc1(String fileloc1) {
        this.fileloc1 = fileloc1 == null ? null : fileloc1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.FILESIZE1
     *
     * @return the value of SKYPG.MSG_QUEUE.FILESIZE1
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Long getFilesize1() {
        return filesize1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.FILESIZE1
     *
     * @param filesize1 the value for SKYPG.MSG_QUEUE.FILESIZE1
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setFilesize1(Long filesize1) {
        this.filesize1 = filesize1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.FILELOC2
     *
     * @return the value of SKYPG.MSG_QUEUE.FILELOC2
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getFileloc2() {
        return fileloc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.FILELOC2
     *
     * @param fileloc2 the value for SKYPG.MSG_QUEUE.FILELOC2
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setFileloc2(String fileloc2) {
        this.fileloc2 = fileloc2 == null ? null : fileloc2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.FILESIZE2
     *
     * @return the value of SKYPG.MSG_QUEUE.FILESIZE2
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Long getFilesize2() {
        return filesize2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.FILESIZE2
     *
     * @param filesize2 the value for SKYPG.MSG_QUEUE.FILESIZE2
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setFilesize2(Long filesize2) {
        this.filesize2 = filesize2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.FILELOC3
     *
     * @return the value of SKYPG.MSG_QUEUE.FILELOC3
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getFileloc3() {
        return fileloc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.FILELOC3
     *
     * @param fileloc3 the value for SKYPG.MSG_QUEUE.FILELOC3
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setFileloc3(String fileloc3) {
        this.fileloc3 = fileloc3 == null ? null : fileloc3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.FILESIZE3
     *
     * @return the value of SKYPG.MSG_QUEUE.FILESIZE3
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Long getFilesize3() {
        return filesize3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.FILESIZE3
     *
     * @param filesize3 the value for SKYPG.MSG_QUEUE.FILESIZE3
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setFilesize3(Long filesize3) {
        this.filesize3 = filesize3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.FILELOC4
     *
     * @return the value of SKYPG.MSG_QUEUE.FILELOC4
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getFileloc4() {
        return fileloc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.FILELOC4
     *
     * @param fileloc4 the value for SKYPG.MSG_QUEUE.FILELOC4
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setFileloc4(String fileloc4) {
        this.fileloc4 = fileloc4 == null ? null : fileloc4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.FILESIZE4
     *
     * @return the value of SKYPG.MSG_QUEUE.FILESIZE4
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Long getFilesize4() {
        return filesize4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.FILESIZE4
     *
     * @param filesize4 the value for SKYPG.MSG_QUEUE.FILESIZE4
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setFilesize4(Long filesize4) {
        this.filesize4 = filesize4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.FILELOC5
     *
     * @return the value of SKYPG.MSG_QUEUE.FILELOC5
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getFileloc5() {
        return fileloc5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.FILELOC5
     *
     * @param fileloc5 the value for SKYPG.MSG_QUEUE.FILELOC5
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setFileloc5(String fileloc5) {
        this.fileloc5 = fileloc5 == null ? null : fileloc5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.FILESIZE5
     *
     * @return the value of SKYPG.MSG_QUEUE.FILESIZE5
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Long getFilesize5() {
        return filesize5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.FILESIZE5
     *
     * @param filesize5 the value for SKYPG.MSG_QUEUE.FILESIZE5
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setFilesize5(Long filesize5) {
        this.filesize5 = filesize5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.FILECNT_CHECKUP
     *
     * @return the value of SKYPG.MSG_QUEUE.FILECNT_CHECKUP
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Short getFilecntCheckup() {
        return filecntCheckup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.FILECNT_CHECKUP
     *
     * @param filecntCheckup the value for SKYPG.MSG_QUEUE.FILECNT_CHECKUP
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setFilecntCheckup(Short filecntCheckup) {
        this.filecntCheckup = filecntCheckup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.INSERT_TIME
     *
     * @return the value of SKYPG.MSG_QUEUE.INSERT_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.INSERT_TIME
     *
     * @param insertTime the value for SKYPG.MSG_QUEUE.INSERT_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.REQUEST_TIME
     *
     * @return the value of SKYPG.MSG_QUEUE.REQUEST_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Date getRequestTime() {
        return requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.REQUEST_TIME
     *
     * @param requestTime the value for SKYPG.MSG_QUEUE.REQUEST_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setRequestTime(Date requestTime) {
        this.requestTime = requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.SEND_TIME
     *
     * @return the value of SKYPG.MSG_QUEUE.SEND_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.SEND_TIME
     *
     * @param sendTime the value for SKYPG.MSG_QUEUE.SEND_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.REPORT_TIME
     *
     * @return the value of SKYPG.MSG_QUEUE.REPORT_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Date getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.REPORT_TIME
     *
     * @param reportTime the value for SKYPG.MSG_QUEUE.REPORT_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setReportTime(Date reportTime) {
        this.reportTime = reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.TCPRECV_TIME
     *
     * @return the value of SKYPG.MSG_QUEUE.TCPRECV_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Date getTcprecvTime() {
        return tcprecvTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.TCPRECV_TIME
     *
     * @param tcprecvTime the value for SKYPG.MSG_QUEUE.TCPRECV_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setTcprecvTime(Date tcprecvTime) {
        this.tcprecvTime = tcprecvTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.SAVE_TIME
     *
     * @return the value of SKYPG.MSG_QUEUE.SAVE_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Date getSaveTime() {
        return saveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.SAVE_TIME
     *
     * @param saveTime the value for SKYPG.MSG_QUEUE.SAVE_TIME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setSaveTime(Date saveTime) {
        this.saveTime = saveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.TELECOM
     *
     * @return the value of SKYPG.MSG_QUEUE.TELECOM
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getTelecom() {
        return telecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.TELECOM
     *
     * @param telecom the value for SKYPG.MSG_QUEUE.TELECOM
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setTelecom(String telecom) {
        this.telecom = telecom == null ? null : telecom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.RESULT
     *
     * @return the value of SKYPG.MSG_QUEUE.RESULT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.RESULT
     *
     * @param result the value for SKYPG.MSG_QUEUE.RESULT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.REPCNT
     *
     * @return the value of SKYPG.MSG_QUEUE.REPCNT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Integer getRepcnt() {
        return repcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.REPCNT
     *
     * @param repcnt the value for SKYPG.MSG_QUEUE.REPCNT
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setRepcnt(Integer repcnt) {
        this.repcnt = repcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.SERVER_ID
     *
     * @return the value of SKYPG.MSG_QUEUE.SERVER_ID
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Long getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.SERVER_ID
     *
     * @param serverId the value for SKYPG.MSG_QUEUE.SERVER_ID
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setServerId(Long serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.OPT_ID
     *
     * @return the value of SKYPG.MSG_QUEUE.OPT_ID
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getOptId() {
        return optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.OPT_ID
     *
     * @param optId the value for SKYPG.MSG_QUEUE.OPT_ID
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setOptId(String optId) {
        this.optId = optId == null ? null : optId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.OPT_CMP
     *
     * @return the value of SKYPG.MSG_QUEUE.OPT_CMP
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getOptCmp() {
        return optCmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.OPT_CMP
     *
     * @param optCmp the value for SKYPG.MSG_QUEUE.OPT_CMP
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setOptCmp(String optCmp) {
        this.optCmp = optCmp == null ? null : optCmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.OPT_POST
     *
     * @return the value of SKYPG.MSG_QUEUE.OPT_POST
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getOptPost() {
        return optPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.OPT_POST
     *
     * @param optPost the value for SKYPG.MSG_QUEUE.OPT_POST
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setOptPost(String optPost) {
        this.optPost = optPost == null ? null : optPost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.OPT_NAME
     *
     * @return the value of SKYPG.MSG_QUEUE.OPT_NAME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getOptName() {
        return optName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.OPT_NAME
     *
     * @param optName the value for SKYPG.MSG_QUEUE.OPT_NAME
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setOptName(String optName) {
        this.optName = optName == null ? null : optName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.EXT_COL0
     *
     * @return the value of SKYPG.MSG_QUEUE.EXT_COL0
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public Long getExtCol0() {
        return extCol0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.EXT_COL0
     *
     * @param extCol0 the value for SKYPG.MSG_QUEUE.EXT_COL0
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setExtCol0(Long extCol0) {
        this.extCol0 = extCol0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.EXT_COL1
     *
     * @return the value of SKYPG.MSG_QUEUE.EXT_COL1
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getExtCol1() {
        return extCol1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.EXT_COL1
     *
     * @param extCol1 the value for SKYPG.MSG_QUEUE.EXT_COL1
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setExtCol1(String extCol1) {
        this.extCol1 = extCol1 == null ? null : extCol1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.EXT_COL2
     *
     * @return the value of SKYPG.MSG_QUEUE.EXT_COL2
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getExtCol2() {
        return extCol2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.EXT_COL2
     *
     * @param extCol2 the value for SKYPG.MSG_QUEUE.EXT_COL2
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setExtCol2(String extCol2) {
        this.extCol2 = extCol2 == null ? null : extCol2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.EXT_COL3
     *
     * @return the value of SKYPG.MSG_QUEUE.EXT_COL3
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getExtCol3() {
        return extCol3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.EXT_COL3
     *
     * @param extCol3 the value for SKYPG.MSG_QUEUE.EXT_COL3
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setExtCol3(String extCol3) {
        this.extCol3 = extCol3 == null ? null : extCol3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.SITE_CD
     *
     * @return the value of SKYPG.MSG_QUEUE.SITE_CD
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getSiteCd() {
        return siteCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.SITE_CD
     *
     * @param siteCd the value for SKYPG.MSG_QUEUE.SITE_CD
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setSiteCd(String siteCd) {
        this.siteCd = siteCd == null ? null : siteCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.MSG_QUEUE.CORP_ID
     *
     * @return the value of SKYPG.MSG_QUEUE.CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public String getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.MSG_QUEUE.CORP_ID
     *
     * @param corpId the value for SKYPG.MSG_QUEUE.CORP_ID
     *
     * @mbg.generated Thu Sep 10 09:54:32 KST 2020
     */
    public void setCorpId(String corpId) {
        this.corpId = corpId == null ? null : corpId.trim();
    }
}