package com.dzpay.admin.mapper;

import java.util.List;

import com.dzpay.admin.common.dto.host.TblhostInfo;

public interface TblhostInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKYPG.TBLHOST_INFO
	 * @mbg.generated  Fri Sep 04 15:43:27 KST 2020
	 */
	int insert(TblhostInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKYPG.TBLHOST_INFO
	 * @mbg.generated  Fri Sep 04 15:43:27 KST 2020
	 */
	List<TblhostInfo> selectAll();
}