package com.dzpay.admin.mapper;

import com.dzpay.admin.common.dto.token.auth.TblofficeAdminToken;
import java.util.List;

public interface TblofficeAdminTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKYPG.TBLOFFICE_ADMIN_TOKEN
     *
     * @mbg.generated Tue Sep 15 17:47:13 KST 2020
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKYPG.TBLOFFICE_ADMIN_TOKEN
     *
     * @mbg.generated Tue Sep 15 17:47:13 KST 2020
     */
    int insert(TblofficeAdminToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKYPG.TBLOFFICE_ADMIN_TOKEN
     *
     * @mbg.generated Tue Sep 15 17:47:13 KST 2020
     */
    TblofficeAdminToken selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKYPG.TBLOFFICE_ADMIN_TOKEN
     *
     * @mbg.generated Tue Sep 15 17:47:13 KST 2020
     */
    List<TblofficeAdminToken> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKYPG.TBLOFFICE_ADMIN_TOKEN
     *
     * @mbg.generated Tue Sep 15 17:47:13 KST 2020
     */
    int updateByPrimaryKey(TblofficeAdminToken record);
}