package com.dzpay.admin.common.dto.post;

public class TbletcPost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLETC_POST.ZIPCODE_SEQ
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    private int zipcodeSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLETC_POST.ZIPCODE
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    private String zipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLETC_POST.SIDO
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    private String sido;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLETC_POST.GUGUN
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    private String gugun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLETC_POST.DONG
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    private String dong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLETC_POST.BUNJI
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    private String bunji;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLETC_POST.ZIPCODE_SEQ
     *
     * @return the value of SKYPG.TBLETC_POST.ZIPCODE_SEQ
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    public int getZipcodeSeq() {
        return zipcodeSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLETC_POST.ZIPCODE_SEQ
     *
     * @param zipcodeSeq the value for SKYPG.TBLETC_POST.ZIPCODE_SEQ
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    public void setZipcodeSeq(int zipcodeSeq) {
        this.zipcodeSeq = zipcodeSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLETC_POST.ZIPCODE
     *
     * @return the value of SKYPG.TBLETC_POST.ZIPCODE
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLETC_POST.ZIPCODE
     *
     * @param zipcode the value for SKYPG.TBLETC_POST.ZIPCODE
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLETC_POST.SIDO
     *
     * @return the value of SKYPG.TBLETC_POST.SIDO
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    public String getSido() {
        return sido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLETC_POST.SIDO
     *
     * @param sido the value for SKYPG.TBLETC_POST.SIDO
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    public void setSido(String sido) {
        this.sido = sido == null ? null : sido.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLETC_POST.GUGUN
     *
     * @return the value of SKYPG.TBLETC_POST.GUGUN
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    public String getGugun() {
        return gugun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLETC_POST.GUGUN
     *
     * @param gugun the value for SKYPG.TBLETC_POST.GUGUN
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    public void setGugun(String gugun) {
        this.gugun = gugun == null ? null : gugun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLETC_POST.DONG
     *
     * @return the value of SKYPG.TBLETC_POST.DONG
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    public String getDong() {
        return dong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLETC_POST.DONG
     *
     * @param dong the value for SKYPG.TBLETC_POST.DONG
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    public void setDong(String dong) {
        this.dong = dong == null ? null : dong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLETC_POST.BUNJI
     *
     * @return the value of SKYPG.TBLETC_POST.BUNJI
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    public String getBunji() {
        return bunji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLETC_POST.BUNJI
     *
     * @param bunji the value for SKYPG.TBLETC_POST.BUNJI
     *
     * @mbg.generated Thu Sep 03 15:14:22 KST 2020
     */
    public void setBunji(String bunji) {
        this.bunji = bunji == null ? null : bunji.trim();
    }
}