package com.dzpay.admin.common.dto.token.auth;

import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;

import javax.annotation.Resource;
import javax.inject.Inject;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import com.dzpay.admin.security.JwtTokenProvider;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.ExpiredJwtException;
import io.jsonwebtoken.Jws;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.MalformedJwtException;
import io.jsonwebtoken.SignatureException;
import io.jsonwebtoken.UnsupportedJwtException;

public class TblofficeAdminToken implements UserDetails {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private JwtTokenProvider jwtTokenProvider = new JwtTokenProvider();

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column SKYPG.TBLOFFICE_ADMIN_TOKEN.ID
	 *
	 * @mbg.generated Tue Sep 15 17:47:13 KST 2020
	 */
	private Short id;

	private String adminid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column SKYPG.TBLOFFICE_ADMIN_TOKEN.SITECODE
	 *
	 * @mbg.generated Tue Sep 15 17:47:13 KST 2020
	 */
	private String sitecode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column SKYPG.TBLOFFICE_ADMIN_TOKEN.ACCESSTOKEN
	 *
	 * @mbg.generated Tue Sep 15 17:47:13 KST 2020
	 */
	private String accesstoken;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column SKYPG.TBLOFFICE_ADMIN_TOKEN.CREATEDDATE
	 *
	 * @mbg.generated Tue Sep 15 17:47:13 KST 2020
	 */
	private Date createddate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column SKYPG.TBLOFFICE_ADMIN_TOKEN.MODIFIEDDATE
	 *
	 * @mbg.generated Tue Sep 15 17:47:13 KST 2020
	 */
	private Date modifieddate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column SKYPG.TBLOFFICE_ADMIN_TOKEN.ID
	 *
	 * @return the value of SKYPG.TBLOFFICE_ADMIN_TOKEN.ID
	 *
	 * @mbg.generated Tue Sep 15 17:47:13 KST 2020
	 */
	public Short getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column SKYPG.TBLOFFICE_ADMIN_TOKEN.ID
	 *
	 * @param id the value for SKYPG.TBLOFFICE_ADMIN_TOKEN.ID
	 *
	 * @mbg.generated Tue Sep 15 17:47:13 KST 2020
	 */
	public void setId(Short id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column SKYPG.TBLOFFICE_ADMIN_TOKEN.SITECODE
	 *
	 * @return the value of SKYPG.TBLOFFICE_ADMIN_TOKEN.SITECODE
	 *
	 * @mbg.generated Tue Sep 15 17:47:13 KST 2020
	 */
	public String getSitecode() {
		return sitecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column SKYPG.TBLOFFICE_ADMIN_TOKEN.SITECODE
	 *
	 * @param sitecode the value for SKYPG.TBLOFFICE_ADMIN_TOKEN.SITECODE
	 *
	 * @mbg.generated Tue Sep 15 17:47:13 KST 2020
	 */
	public void setSitecode(String sitecode) {
		this.sitecode = sitecode == null ? null : sitecode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column SKYPG.TBLOFFICE_ADMIN_TOKEN.ACCESSTOKEN
	 *
	 * @return the value of SKYPG.TBLOFFICE_ADMIN_TOKEN.ACCESSTOKEN
	 *
	 * @mbg.generated Tue Sep 15 17:47:13 KST 2020
	 */
	public String getAccesstoken() {
		return accesstoken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column SKYPG.TBLOFFICE_ADMIN_TOKEN.ACCESSTOKEN
	 *
	 * @param accesstoken the value for SKYPG.TBLOFFICE_ADMIN_TOKEN.ACCESSTOKEN
	 *
	 * @mbg.generated Tue Sep 15 17:47:13 KST 2020
	 */
	public void setAccesstoken(String accesstoken) {
		this.accesstoken = accesstoken == null ? null : accesstoken.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column SKYPG.TBLOFFICE_ADMIN_TOKEN.CREATEDDATE
	 *
	 * @return the value of SKYPG.TBLOFFICE_ADMIN_TOKEN.CREATEDDATE
	 *
	 * @mbg.generated Tue Sep 15 17:47:13 KST 2020
	 */
	public Date getCreateddate() {
		return createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column SKYPG.TBLOFFICE_ADMIN_TOKEN.CREATEDDATE
	 *
	 * @param createddate the value for SKYPG.TBLOFFICE_ADMIN_TOKEN.CREATEDDATE
	 *
	 * @mbg.generated Tue Sep 15 17:47:13 KST 2020
	 */
	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column SKYPG.TBLOFFICE_ADMIN_TOKEN.MODIFIEDDATE
	 *
	 * @return the value of SKYPG.TBLOFFICE_ADMIN_TOKEN.MODIFIEDDATE
	 *
	 * @mbg.generated Tue Sep 15 17:47:13 KST 2020
	 */
	public Date getModifieddate() {
		return modifieddate;
	}

	public String getAdminid() {
		return adminid;
	}

	public void setAdminid(String adminId) {
		this.adminid = adminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column SKYPG.TBLOFFICE_ADMIN_TOKEN.MODIFIEDDATE
	 *
	 * @param modifieddate the value for SKYPG.TBLOFFICE_ADMIN_TOKEN.MODIFIEDDATE
	 *
	 * @mbg.generated Tue Sep 15 17:47:13 KST 2020
	 */
	public void setModifieddate(Date modifieddate) {
		this.modifieddate = modifieddate;
	}

	// 계정의 권한
	@Override
	public Collection<? extends GrantedAuthority> getAuthorities() {
		System.out.println(this.accesstoken);
		// 익밍의 사용자
		String userRole = "ANANYMOUS";
		try {
			userRole = jwtTokenProvider.getUserRole(this.accesstoken);
		} catch (ExpiredJwtException | UnsupportedJwtException | MalformedJwtException | SignatureException
				| IllegalArgumentException | UnsupportedEncodingException e) {
			e.printStackTrace();
		}
		String roleGrant = "ROLE_" + userRole;
		System.out.println("USER's Role " + roleGrant);
		GrantedAuthority myGrant = new SimpleGrantedAuthority(roleGrant);
		GrantedAuthority tokenGrant = new SimpleGrantedAuthority(this.accesstoken);
		List<GrantedAuthority> authorities = new ArrayList<>();
		authorities.add(myGrant);
		authorities.add(tokenGrant);
		return authorities;
	}

	@Override
	public String getPassword() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String getUsername() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean isAccountNonExpired() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean isAccountNonLocked() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean isCredentialsNonExpired() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean isEnabled() {
		// TODO Auto-generated method stub
		return false;
	}
}