package com.dzpay.admin.common.dto.host;

import java.util.Date;

public class TblhostInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.SITE_HOSTING_ID
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String siteHostingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.HOST_NM
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String hostNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.TYPE_GUBN
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String typeGubn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.HOST_CORP_ID
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String hostCorpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.APPLY_CONTACT_YN
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String applyContactYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.DEV_CONTACT_YN
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String devContactYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.CHG_NM
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String chgNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.CHG_TEL
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String chgTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.CHG_EMAIL1
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String chgEmail1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.CHG_EMAIL2
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String chgEmail2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.JOIN_MONY
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private Short joinMony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.YEAR_MONY
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private Short yearMony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.FEE_MONY
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private Short feeMony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.HOST_FEE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private Short hostFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.JOIN_MONY_DIST
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private Short joinMonyDist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.GUARANTEE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private Short guarantee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.PKG_MONTH
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private Short pkgMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.INSURE_MONY
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private Short insureMony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.USE_YN
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String useYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.ETCS
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String etcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.REG_ID
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String regId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.REG_IP
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String regIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.REG_DT
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private Date regDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.TERM_GUBN
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String termGubn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.MOD_DT
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private Date modDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.SALE_DT
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private Short saleDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.ECOMMERCE_NO
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String ecommerceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.FIX_RATE_FEE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private Short fixRateFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.FIX_AMOUNT_FEE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private Short fixAmountFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.CARD_FEE_TYPE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String cardFeeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLHOST_INFO.HOST_SALE_TYPE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    private String hostSaleType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.SITE_HOSTING_ID
     *
     * @return the value of SKYPG.TBLHOST_INFO.SITE_HOSTING_ID
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getSiteHostingId() {
        return siteHostingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.SITE_HOSTING_ID
     *
     * @param siteHostingId the value for SKYPG.TBLHOST_INFO.SITE_HOSTING_ID
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setSiteHostingId(String siteHostingId) {
        this.siteHostingId = siteHostingId == null ? null : siteHostingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.HOST_NM
     *
     * @return the value of SKYPG.TBLHOST_INFO.HOST_NM
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getHostNm() {
        return hostNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.HOST_NM
     *
     * @param hostNm the value for SKYPG.TBLHOST_INFO.HOST_NM
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setHostNm(String hostNm) {
        this.hostNm = hostNm == null ? null : hostNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.TYPE_GUBN
     *
     * @return the value of SKYPG.TBLHOST_INFO.TYPE_GUBN
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getTypeGubn() {
        return typeGubn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.TYPE_GUBN
     *
     * @param typeGubn the value for SKYPG.TBLHOST_INFO.TYPE_GUBN
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setTypeGubn(String typeGubn) {
        this.typeGubn = typeGubn == null ? null : typeGubn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.HOST_CORP_ID
     *
     * @return the value of SKYPG.TBLHOST_INFO.HOST_CORP_ID
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getHostCorpId() {
        return hostCorpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.HOST_CORP_ID
     *
     * @param hostCorpId the value for SKYPG.TBLHOST_INFO.HOST_CORP_ID
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setHostCorpId(String hostCorpId) {
        this.hostCorpId = hostCorpId == null ? null : hostCorpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.APPLY_CONTACT_YN
     *
     * @return the value of SKYPG.TBLHOST_INFO.APPLY_CONTACT_YN
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getApplyContactYn() {
        return applyContactYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.APPLY_CONTACT_YN
     *
     * @param applyContactYn the value for SKYPG.TBLHOST_INFO.APPLY_CONTACT_YN
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setApplyContactYn(String applyContactYn) {
        this.applyContactYn = applyContactYn == null ? null : applyContactYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.DEV_CONTACT_YN
     *
     * @return the value of SKYPG.TBLHOST_INFO.DEV_CONTACT_YN
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getDevContactYn() {
        return devContactYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.DEV_CONTACT_YN
     *
     * @param devContactYn the value for SKYPG.TBLHOST_INFO.DEV_CONTACT_YN
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setDevContactYn(String devContactYn) {
        this.devContactYn = devContactYn == null ? null : devContactYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.CHG_NM
     *
     * @return the value of SKYPG.TBLHOST_INFO.CHG_NM
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getChgNm() {
        return chgNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.CHG_NM
     *
     * @param chgNm the value for SKYPG.TBLHOST_INFO.CHG_NM
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setChgNm(String chgNm) {
        this.chgNm = chgNm == null ? null : chgNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.CHG_TEL
     *
     * @return the value of SKYPG.TBLHOST_INFO.CHG_TEL
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getChgTel() {
        return chgTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.CHG_TEL
     *
     * @param chgTel the value for SKYPG.TBLHOST_INFO.CHG_TEL
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setChgTel(String chgTel) {
        this.chgTel = chgTel == null ? null : chgTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.CHG_EMAIL1
     *
     * @return the value of SKYPG.TBLHOST_INFO.CHG_EMAIL1
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getChgEmail1() {
        return chgEmail1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.CHG_EMAIL1
     *
     * @param chgEmail1 the value for SKYPG.TBLHOST_INFO.CHG_EMAIL1
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setChgEmail1(String chgEmail1) {
        this.chgEmail1 = chgEmail1 == null ? null : chgEmail1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.CHG_EMAIL2
     *
     * @return the value of SKYPG.TBLHOST_INFO.CHG_EMAIL2
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getChgEmail2() {
        return chgEmail2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.CHG_EMAIL2
     *
     * @param chgEmail2 the value for SKYPG.TBLHOST_INFO.CHG_EMAIL2
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setChgEmail2(String chgEmail2) {
        this.chgEmail2 = chgEmail2 == null ? null : chgEmail2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.JOIN_MONY
     *
     * @return the value of SKYPG.TBLHOST_INFO.JOIN_MONY
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public Short getJoinMony() {
        return joinMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.JOIN_MONY
     *
     * @param joinMony the value for SKYPG.TBLHOST_INFO.JOIN_MONY
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setJoinMony(Short joinMony) {
        this.joinMony = joinMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.YEAR_MONY
     *
     * @return the value of SKYPG.TBLHOST_INFO.YEAR_MONY
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public Short getYearMony() {
        return yearMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.YEAR_MONY
     *
     * @param yearMony the value for SKYPG.TBLHOST_INFO.YEAR_MONY
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setYearMony(Short yearMony) {
        this.yearMony = yearMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.FEE_MONY
     *
     * @return the value of SKYPG.TBLHOST_INFO.FEE_MONY
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public Short getFeeMony() {
        return feeMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.FEE_MONY
     *
     * @param feeMony the value for SKYPG.TBLHOST_INFO.FEE_MONY
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setFeeMony(Short feeMony) {
        this.feeMony = feeMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.HOST_FEE
     *
     * @return the value of SKYPG.TBLHOST_INFO.HOST_FEE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public Short getHostFee() {
        return hostFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.HOST_FEE
     *
     * @param hostFee the value for SKYPG.TBLHOST_INFO.HOST_FEE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setHostFee(Short hostFee) {
        this.hostFee = hostFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.JOIN_MONY_DIST
     *
     * @return the value of SKYPG.TBLHOST_INFO.JOIN_MONY_DIST
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public Short getJoinMonyDist() {
        return joinMonyDist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.JOIN_MONY_DIST
     *
     * @param joinMonyDist the value for SKYPG.TBLHOST_INFO.JOIN_MONY_DIST
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setJoinMonyDist(Short joinMonyDist) {
        this.joinMonyDist = joinMonyDist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.GUARANTEE
     *
     * @return the value of SKYPG.TBLHOST_INFO.GUARANTEE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public Short getGuarantee() {
        return guarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.GUARANTEE
     *
     * @param guarantee the value for SKYPG.TBLHOST_INFO.GUARANTEE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setGuarantee(Short guarantee) {
        this.guarantee = guarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.PKG_MONTH
     *
     * @return the value of SKYPG.TBLHOST_INFO.PKG_MONTH
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public Short getPkgMonth() {
        return pkgMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.PKG_MONTH
     *
     * @param pkgMonth the value for SKYPG.TBLHOST_INFO.PKG_MONTH
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setPkgMonth(Short pkgMonth) {
        this.pkgMonth = pkgMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.INSURE_MONY
     *
     * @return the value of SKYPG.TBLHOST_INFO.INSURE_MONY
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public Short getInsureMony() {
        return insureMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.INSURE_MONY
     *
     * @param insureMony the value for SKYPG.TBLHOST_INFO.INSURE_MONY
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setInsureMony(Short insureMony) {
        this.insureMony = insureMony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.USE_YN
     *
     * @return the value of SKYPG.TBLHOST_INFO.USE_YN
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.USE_YN
     *
     * @param useYn the value for SKYPG.TBLHOST_INFO.USE_YN
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn == null ? null : useYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.ETCS
     *
     * @return the value of SKYPG.TBLHOST_INFO.ETCS
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getEtcs() {
        return etcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.ETCS
     *
     * @param etcs the value for SKYPG.TBLHOST_INFO.ETCS
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setEtcs(String etcs) {
        this.etcs = etcs == null ? null : etcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.REG_ID
     *
     * @return the value of SKYPG.TBLHOST_INFO.REG_ID
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.REG_ID
     *
     * @param regId the value for SKYPG.TBLHOST_INFO.REG_ID
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setRegId(String regId) {
        this.regId = regId == null ? null : regId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.REG_IP
     *
     * @return the value of SKYPG.TBLHOST_INFO.REG_IP
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getRegIp() {
        return regIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.REG_IP
     *
     * @param regIp the value for SKYPG.TBLHOST_INFO.REG_IP
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setRegIp(String regIp) {
        this.regIp = regIp == null ? null : regIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.REG_DT
     *
     * @return the value of SKYPG.TBLHOST_INFO.REG_DT
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public Date getRegDt() {
        return regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.REG_DT
     *
     * @param regDt the value for SKYPG.TBLHOST_INFO.REG_DT
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setRegDt(Date regDt) {
        this.regDt = regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.TERM_GUBN
     *
     * @return the value of SKYPG.TBLHOST_INFO.TERM_GUBN
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getTermGubn() {
        return termGubn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.TERM_GUBN
     *
     * @param termGubn the value for SKYPG.TBLHOST_INFO.TERM_GUBN
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setTermGubn(String termGubn) {
        this.termGubn = termGubn == null ? null : termGubn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.MOD_DT
     *
     * @return the value of SKYPG.TBLHOST_INFO.MOD_DT
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public Date getModDt() {
        return modDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.MOD_DT
     *
     * @param modDt the value for SKYPG.TBLHOST_INFO.MOD_DT
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setModDt(Date modDt) {
        this.modDt = modDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.SALE_DT
     *
     * @return the value of SKYPG.TBLHOST_INFO.SALE_DT
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public Short getSaleDt() {
        return saleDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.SALE_DT
     *
     * @param saleDt the value for SKYPG.TBLHOST_INFO.SALE_DT
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setSaleDt(Short saleDt) {
        this.saleDt = saleDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.ECOMMERCE_NO
     *
     * @return the value of SKYPG.TBLHOST_INFO.ECOMMERCE_NO
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getEcommerceNo() {
        return ecommerceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.ECOMMERCE_NO
     *
     * @param ecommerceNo the value for SKYPG.TBLHOST_INFO.ECOMMERCE_NO
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setEcommerceNo(String ecommerceNo) {
        this.ecommerceNo = ecommerceNo == null ? null : ecommerceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.FIX_RATE_FEE
     *
     * @return the value of SKYPG.TBLHOST_INFO.FIX_RATE_FEE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public Short getFixRateFee() {
        return fixRateFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.FIX_RATE_FEE
     *
     * @param fixRateFee the value for SKYPG.TBLHOST_INFO.FIX_RATE_FEE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setFixRateFee(Short fixRateFee) {
        this.fixRateFee = fixRateFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.FIX_AMOUNT_FEE
     *
     * @return the value of SKYPG.TBLHOST_INFO.FIX_AMOUNT_FEE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public Short getFixAmountFee() {
        return fixAmountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.FIX_AMOUNT_FEE
     *
     * @param fixAmountFee the value for SKYPG.TBLHOST_INFO.FIX_AMOUNT_FEE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setFixAmountFee(Short fixAmountFee) {
        this.fixAmountFee = fixAmountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.CARD_FEE_TYPE
     *
     * @return the value of SKYPG.TBLHOST_INFO.CARD_FEE_TYPE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getCardFeeType() {
        return cardFeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.CARD_FEE_TYPE
     *
     * @param cardFeeType the value for SKYPG.TBLHOST_INFO.CARD_FEE_TYPE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setCardFeeType(String cardFeeType) {
        this.cardFeeType = cardFeeType == null ? null : cardFeeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLHOST_INFO.HOST_SALE_TYPE
     *
     * @return the value of SKYPG.TBLHOST_INFO.HOST_SALE_TYPE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public String getHostSaleType() {
        return hostSaleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLHOST_INFO.HOST_SALE_TYPE
     *
     * @param hostSaleType the value for SKYPG.TBLHOST_INFO.HOST_SALE_TYPE
     *
     * @mbg.generated Fri Sep 04 15:43:27 KST 2020
     */
    public void setHostSaleType(String hostSaleType) {
        this.hostSaleType = hostSaleType == null ? null : hostSaleType.trim();
    }
}